svelte media bindings
sveltejs/language-tools pull request #502
Opened 2020-08-30 05:25 UTC by jasonlyu123

#500

2020-08-30 05:31 UTC, jasonlyu123 commented
The `readonly` modifier isn't needed. It's just for documentation purposes. And it could be easiler for future works if someday we can typecheck readonly props.

2020-08-30 12:22 UTC, dummdidumm requested changes
Nice idea of not having it as part of the big `HTMLAttributes` list 👍  I suggested some lowercase changes because all props are lowercased by `svelte2tsx`. Also some properties which are on `HTMLAttributes`, like `defaultplaybackrate`, should be moved into this new interface I think.

2020-08-30 12:22 UTC, dummdidumm commented on packages/svelte2tsx/svelte-jsx.d.ts
> +        currentTime?: number;
```suggestion
        currenttime?: number;
```

2020-08-30 12:22 UTC, dummdidumm commented on packages/svelte2tsx/svelte-jsx.d.ts
> +        playbackRate?: number;
```suggestion
        playbackrate?: number;
```

2020-08-30 12:22 UTC, dummdidumm commented on packages/svelte2tsx/svelte-jsx.d.ts
> +        readonly videoWidth?: number;
```suggestion
        readonly videowidth?: number;
```

2020-08-30 12:22 UTC, dummdidumm commented on packages/svelte2tsx/svelte-jsx.d.ts
> +        readonly videoHeight?: number;
```suggestion
        readonly videoheight?: number;
```

2020-08-30 14:13 UTC, jasonlyu123 commented
I have to look into it. all lowercase would have typescript errors on two way binding but camel case won't have error in both props and two way binding.

2020-08-31 01:49 UTC, jasonlyu123 commented
two-way binding is not being transformed to all lowercase. Another problem is most of these camel case props are not HTML attributes but svelte props. The compiler would complain when you use all lower cases which means the autocomplete is wrong.

2020-08-31 05:46 UTC, dummdidumm commented
Damn that's tricky ... About the autocompletion: We could try to turn of autocompletion for all JSX intrinsic elements, they should be shown anyway through the html language service. This would have the additional benefit of not everything showing up twice. If that works, you could just have two variants inside the JSX typings - one all lowercase for the attribute, one camelcased for the binding.

2020-08-31 06:11 UTC, dummdidumm commented
I just noticed that the fix in #496 for #494 has the same problem (so #494 is not fixed yet). My bad.

2020-08-31 10:11 UTC, jasonlyu123 commented
What do you think about also transform two-way binding to lowercase?  We can let the svelte compiler validate the casing on the binding on the svelte-specific props.

2020-08-31 10:54 UTC, dummdidumm commented
Good idea, I think this will work. It's transformed to a simple input property, so we can lowercase it like we do with the real input properties. But we should only do this for html elements, not component elements.

2020-09-01 01:19 UTC, jasonlyu123 commented
It seems like only binding is case-sensitive that's just put two variant as you suggest earlier

2020-09-01 05:21 UTC, jasonlyu123 commented
Some of it doesn't work when used as HTML attribute. It seems like they are svelte spefic props. So I removed the lowercase variant 
```svelte
<script>let playbackRate = 1</script>
<video playbackRate={1} /> <!--doesn't work -->
<video bind:playbackRate /> <!--work -->
```

2020-09-01 05:24 UTC, dummdidumm approved these changes
👍

2020-09-01 05:26 UTC, merged