Selection range
sveltejs/language-tools pull request #583
Opened 2020-10-01 14:35 UTC by jasonlyu123

#556 
The selection range seems to support multiple cursors, so the execution should be done in an `array.map` manner. Because of that, I didn't make the `PluginHost` implementing the same interface. Haven done the typescript part. Probably need to done a similar filtering like `getDocumentSymbols`

2020-10-12 07:49 UTC, dummdidumm requested changes
Looks good to me. There is one bug though in `getSelectionRange` of the `SveltePlugin`: The position has to be mapped to the generated position first.

2020-10-12 07:49 UTC, dummdidumm commented on packages/language-server/src/plugins/svelte/features/getSelectionRanges.ts
> +            // let other plugin done it
```suggestion
            // let other plugins do it
```

2020-10-12 07:49 UTC, dummdidumm commented on packages/language-server/src/plugins/PluginHost.ts
> +    async getSelectionRanges(
Could you add a small comment above the function briefly explaining why this is a special case and the ranges have to be accumulated like this?

2020-10-12 07:49 UTC, dummdidumm commented on packages/language-server/src/plugins/svelte/features/getSelectionRanges.ts
> +    const offset = svelteDoc.offsetAt(position);
The offset here is wrong. The position has to be converted to a generated position first. For that you need to enhance the mappers inside `SvelteDocument` to support `getGeneratedPosition`.

2020-10-17 08:54 UTC, dummdidumm commented
Should I do another review or are there some things missing you want to do first?

2020-10-17 14:44 UTC, jasonlyu123 commented
Ok! It's ready for review again.

2020-10-18 17:34 UTC, dummdidumm approved these changes
👍

2020-10-18 17:34 UTC, merged