ignore html end-tag-like inside moustache
sveltejs/language-tools pull request #671
Opened 2020-11-13 10:08 UTC by jasonlyu123

related #309 

kind of hacky, but it would fix some situation where style tag not being extracted when it's after a self-closed tag with a arrow function props or a event handler.
```svelte
<Foo on:click={() => console.log('yeah!!!')} />
<style></style>
```
There're cases like this:
```svelte
<Foo selected={a > b} />
```
not being covered, But I think dealing with that with this method would have a higher change removing the actual tag end.

Another approach is to use `html-language-service`'s internal api, like [this branch](https://github.com/jasonlyu123/language-tools/blob/enhance-parser-internal/packages/language-server/src/lib/documents/parseHtml.ts)

Or we can alter the `html-language-service`'s `htmlScanner`. [vetur](https://github.com/vuejs/vetur/blob/master/server/src/modes/template/parser/htmlScanner.ts) has a similar scanner to [it](https://github.com/microsoft/vscode-html-languageservice/blob/master/src/parser/htmlScanner.ts).

2020-11-17 09:12 UTC, dummdidumm commented
Altering the Scanner seems more robust but more maintenance work in the future. Your preprocessor step looks good for me since it only blanks moustache tags if I understand that correctly (maybe you could add a short JSDoc above the preprocessor function explaining why it's needed and what is done). The only downside is that it may be a very small performance hit since we now parse the string twice, but I guess that's negligible.
(Maybe we need some kind of performance tests some day)

2020-11-17 14:03 UTC, jasonlyu123 commented
It actally not only blank moustache. This scanner basically goes through the code and compare the code character by character to given char code and condition. 
```svelte
<a on:click={() =>| console.log('a')}></a>
|<div></div>
```
if the scanner sees a '>' inside a tag it would think the tag is closed. So until the next token would be the next open tag, the content (for example the code between two `|` ) would all be considered as text content. By using this method it would blank the valid end of start/end tag. that's why it can only deal with `=>` and `<=`

The internal code of the `html-language-service` actually has an `initialState` parameter by using that we can reset the state and make it restart the scan like it's still within the tag. it would have a higher chance of finding out the actual end of the start tag. it could cover the bigger-than case:
```
<Foo selected={a > b} />
```

2020-11-18 08:55 UTC, jasonlyu123 commented
I use the version utilized `html-language-service` internal API instead

2020-11-18 15:10 UTC, dummdidumm requested changes
Could you add two more test cases testing the "normal" cases (html without a moustache tag, html with a moustache tag but no > character)?
Also does it work correctly for `<div checked={a < 1}></div><style></style>`? A test for that would be good, too.

2020-11-19 06:51 UTC, jasonlyu123 commented
Thanks! added the support

2020-11-19 07:21 UTC, dummdidumm approved these changes

2020-11-19 07:22 UTC, merged