(feat) infer slot/events type from props
sveltejs/language-tools pull request #952
Opened 2021-04-21 07:38 UTC by dummdidumm

This changes the generation for accessing the events/slots of a component. Instead of using `instanceOf`, the component instance is created using the constructor and passing the props. This enables TypeScript to infer generic relationships between props and slots/events.
#945
Note that this change does not cover all cases: If someone forwards a slot or an event whose type is generic and needs to be infered, that type will remain unknown, because reinstantiating the context in the `return { props: .. }` step is really hard.

2021-04-21 09:22 UTC, jasonlyu123 commented
The only solution I can think of now is to declare a new variable. Something similar to if-scope or pass it as a parameter to an immediately invoked function.
```ts
const __propsArgs = { a }
() =>{  
  const a = new Component({ props: __propsArgs  }).$$slotdef['default']
}
```
or

```ts
((__propsArgs) =>{  
  const a = new Component({ props: __propsArgs  }).$$slotdef['default']
})({ a })
```

2021-04-21 16:09 UTC, dummdidumm commented
Yeah sounds like the only option. So there needs to be some logic to track which props there are both on the default and the names slots, and if there's one that's duplicated, construct a immediately invoked function from the default slot and reuse that in all the inner slots.

2021-04-22 14:49 UTC, dummdidumm commented
Ok I reused the ifScope logic here, worked out well, although I still feel that this code is getting more and more complex - if it's just inevitable or I'm writing shitty code, can't tell for sure right now 😄 @jasonlyu123 could you have a look?

2021-04-23 04:07 UTC, jasonlyu123 requested changes
Mostly working great. Found a small problem when an attribute is empty. And some minor issues to discuss.

2021-04-23 07:12 UTC, dummdidumm commented on packages/svelte2tsx/src/htmlxtojsx/utils/node-utils.ts
> +            const value =
Damn, you are completely right, this is just a string in the end and we can simplify this!

2021-04-23 07:37 UTC, dummdidumm commented
These were great suggestions, thanks! Especially that string template comment was a moment of enlightment 😄

2021-04-23 07:40 UTC, merged

2021-04-23 16:09 UTC, ryu-man commented
I noticed that a string value is inferred as "any" type in the slot prop!

2021-04-23 16:46 UTC, dummdidumm commented
Should be fixed with the latest release

2021-04-23 19:21 UTC, ryu-man commented
I am using the latest release, all values get inferred normally, but when using a string value it inferred as "any" type not "string" type

2021-04-24 14:08 UTC, dummdidumm commented
Can't reproduce. What's your version? Latest is 104.10.1 . If the issue persists after restarting VS Code, please open a separate issue with detailed instructions.

2021-04-24 23:32 UTC, ryu-man commented
Great, I tried that one more time and it's working fine now.